pythonWeb/education_project/education_project/urls.py
from django.contrib import admin
from django.urls import re_path, include

urlpatterns = [
    re_path(r'admin/', admin.site.urls),
    re_path(r'^', include('first_app.urls')),
]

pythonWeb/education_project/first_app/urls.py
from django.urls import re_path, include
from .views import *


urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^remen$', remen, name='remen'),
    re_path(r'^article/$', article, name='article'),
    re_path(r'^course/$', course, name='cousre'),
    re_path(r'^courseVideo/$', courseVideo, name='courseVideo'),
    re_path(r'my$', my, name='my'),
    re_path(r'^author',author,name='author'),
    re_path(r'^comment',comment,name='comment'),
    re_path(r'userLead', userLead, name='userLead'),
    re_path(r'^login$', login, name='login'),
    re_path(r'^articleAdd$', articleAdd, name='articleAdd'),
    re_path(r'^jingdong$', jingdong, name='jingdong'),
    re_path(r'^ouwang$', ouwang, name='ouwang'),
]

pythonWeb/education_project/first_app/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

# 用户模型.
class User(AbstractUser):

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']
        
    def __str__(self):
        return self.username
    
    
class proUser(models.Model):
    name = models.CharField(max_length=30, verbose_name='用户名称')
    pasw = models.CharField(max_length=30, verbose_name='密码')
    class Meta:
        verbose_name = '普通用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name
    
# tag（标签）
class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='标签名称')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name
    
# 分类
class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='分类名称')
    index = models.IntegerField(default=999,verbose_name='分类的排序')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['index', 'id']

    def __str__(self):
        return self.name
    
# 文章模型
class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=50, verbose_name='文章描述')
    content = models.TextField(verbose_name='文章内容')
    click_count = models.IntegerField(default=0, verbose_name='点击次数')
    is_recommend = models.BooleanField(default=False, verbose_name='是否推荐')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    user = models.ForeignKey(User, verbose_name='用户',on_delete=models.CASCADE)
    category = models.ForeignKey(Category, blank=True, null=True, verbose_name='分类',on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, verbose_name='标签')

    # objects = ArticleManager()

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def __str__(self):
        return self.title
    
# 评论模型
class Comment(models.Model):
    content = models.TextField(verbose_name='评论内容')
    username = models.CharField(max_length=30, blank=True, null=True, verbose_name='用户名')
    email = models.EmailField(max_length=50, blank=True, null=True, verbose_name='邮箱地址')
    url = models.URLField(max_length=100, blank=True, null=True, verbose_name='个人网页地址')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    user = models.ForeignKey(User, blank=True, null=True, verbose_name='用户',on_delete=models.CASCADE)
    article = models.ForeignKey(Article, blank=True, null=True, verbose_name='文章',on_delete=models.CASCADE)
    pid = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.id)
    
# 教程
class Course(models.Model):
    title = models.CharField(max_length=50, verbose_name='教程标题')
    click_count = models.IntegerField(default=0, verbose_name='点击次数')
    desc = models.CharField(max_length=100, blank=True,verbose_name='描述')
        
    class Meta:
        verbose_name = '教程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title
    
# 教程目录内容
class CourseList(models.Model):
    catalog = models.CharField(max_length=50, verbose_name='目录标题')
    index = models.IntegerField(default=999,verbose_name='目录的排序')
    course_title = models.ForeignKey(Course, blank=True, null=True, verbose_name='教程标题',on_delete=models.CASCADE)
    content = models.TextField(verbose_name='目录内容')
    
    class Meta:
        verbose_name = '教程目录'
        verbose_name_plural = verbose_name
        ordering = ['index']
        

    def __str__(self):
        return self.catalog
 
    
        
# 教程视频
class CourseVideo(models.Model):
    title = models.CharField(max_length=50, verbose_name='教程标题')
    click_count = models.IntegerField(default=0, verbose_name='点击次数')
    desc = models.CharField(max_length=100, verbose_name='描述')
        
    class Meta:
        verbose_name = '教程视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    
# 教程视频目录内容
class CourseVideoList(models.Model):
    catalog = models.CharField(max_length=50, verbose_name='目录标题')
    index = models.IntegerField(default=999,verbose_name='目录的排序')
    courseVideo_title = models.ForeignKey(CourseVideo, blank=True, null=True, verbose_name='教程视频',on_delete=models.CASCADE)
    videoUrl = models.CharField(max_length=100, verbose_name='视频url')
    
    class Meta:
        verbose_name = '教程视频目录内容'
        verbose_name_plural = verbose_name
        ordering = ['index']

    def __str__(self):
        return self.catalog
    
class FirstAppWeixininfo(models.Model):
    title = models.CharField(max_length=100)
    date = models.CharField(max_length=50)
    from_name = models.CharField(max_length=50)
    read_num = models.CharField(max_length=20, blank=True, null=True)
    like_num = models.CharField(max_length=20, blank=True, null=True)
    articleurl = models.CharField(db_column='articleUrl', max_length=350, blank=True, null=True)  # Field name made lowercase.
    shijianchuo = models.CharField(max_length=50)
    digest = models.CharField(max_length=300, blank=True, null=True)
    updete_time = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'first_app_weixininfo'

class Jingdong(models.Model):
    productid = models.CharField(db_column='productId', max_length=100, blank=True, null=True)  # Field name made lowercase.
    productname = models.CharField(db_column='productName', max_length=100, blank=True, null=True)  # Field name made lowercase.
    shopname = models.CharField(db_column='shopName', max_length=100, blank=True, null=True)  # Field name made lowercase.
    commentnums = models.CharField(db_column='commentNums', max_length=100, blank=True, null=True)  # Field name made lowercase.
    prices = models.CharField(max_length=20, blank=True, null=True)
    links = models.CharField(max_length=255, blank=True, null=True)
    imageUrl = models.CharField(max_length=255, blank=True, null=True)	

    class Meta:
        verbose_name = '京东信息'
        verbose_name_plural = verbose_name
        ordering = ['productname']

    def __str__(self):
        return self.productname

class Ouwang(models.Model):
    title = models.CharField(db_column='title', max_length=100, blank=True, null=True)  # Field name made lowercase.
    ctt =  models.CharField(db_column='content', max_length=10000,  verbose_name='文章内容')   # Field name made lowercase.
    date = models.CharField(db_column='date', max_length=100, blank=True, null=True)  # Field name made lowercase.
    visitCount = models.CharField(db_column='visitCount', max_length=100, blank=True, null=True)  # Field name made lowercase.
    LinkUrl = models.CharField(db_column='LinkUrl', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        verbose_name = '瓯网信息'
        verbose_name_plural = verbose_name
        ordering = ['title']

    def __str__(self):
        return self.title

pythonWeb/education_project/templates/ad.html
{% load staticfiles %}
<div class="banner">
      <div id="slide-holder">
        <div id="slide-runner"> 
        <a href="/article/?id=1" target="_blank">
        <img id="slide-img-1" src="{% static 'images/a1.jpg' %}"  alt="" />
        </a> 
        <a href="/article/?id=2" target="_blank">
        <img id="slide-img-2" src="{% static 'images/a2.jpg' %}"  alt="" />
        </a> 
        <a href="/article/?id=4" target="_blank">
        <img id="slide-img-3" src="{% static 'images/a3.jpg' %}"  alt="" />
        </a> 
        <a href="/article/?id=3" target="_blank">
        <img id="slide-img-4" src="{% static 'images/a4.jpg' %}"  alt="" />
        </a>
          <div id="slide-controls">
            <p id="slide-client" class="text"><strong></strong><span></span></p>
            <p id="slide-desc" class="text"></p>
            <p id="slide-nav"></p>
          </div>
        </div>
      </div>
      <script>
    if(!window.slider) {
    var slider={};
  }

  slider.data= [
    {
        "id":"slide-img-1", // 与slide-runner中的img标签id对应
        "client":"Python读写Excel表格",
        "desc":"就是这么简单粗暴又好用" //这里修改描述
    },
    {
        "id":"slide-img-2",
        "client":"Spring 经典面试题和答案",
        "desc":"Spring 经典面试题和答案"
    },
    {
        "id":"slide-img-3",
        "client":"Spring AOP中定义切点",
        "desc":"pring AOP中定义切点（PointCut）和通知（Advice）"
    },
    {
        "id":"slide-img-4",
        "client":"DispatcherServlet详解",
        "desc":"springMVC DispatcherServlet详解"
    }
  ];

    </script>
    </div>
    <!-- banner代码 结束 -->

pythonWeb/education_project/templates/article.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block left_content %}
    <div class="postdate">

      <div class="date">{{ article.date_publish | date:'d' }}</div>
    </div>
    <div class="title">
        <h2><a href="" rel="bookmark" title="{{ article.title }}">{{ article.title }}</a></h2>
        <div class="postmeta">
          <span class="postmeta_author">{{ article.user.username }}</span>
          <span class="postmeta_category"><a href="" rel="category">{{ article.category.name }}</a></span>
          <span class="postmeta_time">{{ article.date_publish | date:'Y-m-d' }}</span>
        </div>
    </div>
        <div class="entry">
          {{ article.content | safe }}
        </div>
        <span class="tags">
            {% for tag in article.tag.all %}
            <a href="?tag={{ tag.name }}" rel="tag">{{ tag.name }}</a>
            {% endfor %}
        </span>
        <div class="info">
        Address:  <a href="{{ SITE_URL }}article/?id={{ article.id }}" rel="bookmark" title="{{ article.title }}">{{ SITE_URL }}article/?id={{ article.id }}</a>
        </div>

      <div class="commentstitle"><h3 id="comments"><span class="commentsnumber">评论  1 comment</span></h3></div>

      





  <div id="respond">
		<form id="comment-form" name="comment-form" action="/article/?id={{ id }}" method="POST">
			<div class="comment">

  <input name="commentId" value="{{ id }}" type="hidden">
				<div class="comment-box">
					<textarea placeholder="您的评论或留言（必填）" name="commentTextarea" id="comment-textarea" cols="100%" rows="10" tabindex="3" style="
  font-size:1.4em;
  height:2.7em;
  border-radius:4px;
  border:1px solid #c8cccf;
  color:#6a6f77;
  outline:0;
  padding:0 1em;    

  width:100%;"></textarea>
					<div class="comment-ctrl">
						<div class="comment-prompt" style="display: none;"> <i class="fa fa-spin fa-circle-o-notch"></i> <span class="comment-prompt-text">评论正在提交中...请稍后</span> </div>
						<div class="comment-success" style="display: none;"> <i class="fa fa-check"></i> <span class="comment-prompt-text">评论提交成功...</span> </div>
						<button  style="width:200px;padding:8px;  
						margin-left:250px;
        background-color: #428bca;  
        border-color: #357ebd;  
        color: #fff;  
        -moz-border-radius: 10px;  
        -webkit-border-radius: 10px;  
        border-radius: 10px; /* future proofing */  
        -khtml-border-radius: 10px; /* for old Konqueror browsers */  
        text-align: center;  
        vertical-align: middle;  
        border: 1px solid transparent;  
        font-weight: 900;  font-size:125%" type="submit" name="comment-submit" id="comment-submit" tabindex="4">评论</button>
					</div>
				</div>
			</div>
		</form>
		
	</div>
  <div id="postcomments">
	<ol id="comment_list" class="commentlist">  
	
	{% for comment in commentList %}
        	<li class="comment-content"><span class="comment-f">#2</span><div class="comment-main"><p><a class="address" href="" rel="nofollow" target="_blank" style="font-size:20px">{{ comment.username }}</a><span class="time" style="font-size:15px">({{ comment.date_publish }})</span><br><p style="font-size:29px">{{ comment.content }}</p></p></div></li>
	
   {% endfor %}      
	 </div>


    
{% endblock %}

pythonWeb/education_project/templates/articleAdd.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en-us" >
<head>
<title>Add 文章 | Django site admin</title>
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />


<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/actions.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/urlify.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/prepopulate.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/vendor/xregexp/xregexp.js' %}"></script>
<script type="text/javascript" src="{% static 'js/kindeditor-4.1.10/kindeditor-min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/kindeditor-4.1.10/lang/zh_CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/kindeditor-4.1.10/config.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/collapse.js' %}"></script>


    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}/static/admin/css/responsive.css" />
    

<meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class=" app-first_app model-article change-form"
  data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name"><a href="/">首页</a></h1>

        </div>
        
       
        
        
    </div>
    <!-- END Header -->
    
<div class="breadcrumbs">
 <h2>{{ username }}添加文章             {{istrue}}</h2>
</div>

    

    
        
    

    <!-- Content -->
    <div id="content" class="colM">
        
        
        <div id="content-main">



<form enctype="multipart/form-data" action="/articleAdd" method="post" id="article_form" novalidate><input type='hidden' name='csrfmiddlewaretoken' value='WZSCvj29nr3hh6opGWcSSFjFnavDL82VOUQmawMs7Mq7OT2nJg9Kj5O1DMTbC5sd' />
<div>







  <fieldset class="module aligned ">
    
    
    
        <div class="form-row field-title">
            
            
                <div>
                    
                    
                        <label class="required" for="id_title">文章标题:</label>
                        
                            <input type="text" name="title" class="vTextField" maxlength="50" required id="id_title" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-desc">
            
            
                <div>
                    
                    
                        <label class="required" for="id_desc">文章描述:</label>
                        
                            <input type="text" name="desc" class="vTextField" maxlength="50" required id="id_desc" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-content">
            
            
                <div>
                    
                    
                        <label class="required" for="id_content">文章内容:</label>
                        
                            <textarea name="content" cols="40" rows="10" class="vLargeTextField" required id="id_content">
</textarea>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-user">
            
            
                <div>
                    
                    
                        <label class="required" for="id_user">用户:</label>
                        
                            <div class="related-widget-wrapper">


{{ username }}

       
    
</div>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-category">
            
            
                <div>
                    
                    
                        <label for="id_category">分类:</label>
                        
                            <div class="related-widget-wrapper">
    <select name="category" id="id_category">
  <option value="" selected>---------</option>

  <option value="1">Python</option>

  <option value="2">spring</option>

  <option value="3">springMVC</option>

  <option value="4">javaSE</option>

  <option value="5">javaEE</option>

  <option value="6">日志</option>

</select>
    
     
    
</div>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-tag">
            
            
                <div>
                    
                    
                        <label class="required" for="id_tag">标签:</label>
                        
                            <div class="related-widget-wrapper">
    <select name="tag" required id="id_tag" multiple="multiple">
  <option value="1">Python</option>

  <option value="2">spring</option>

  <option value="3">springMVC</option>

  <option value="4">javaSE</option>

  <option value="5">javaEE</option>

  <option value="6">java</option>

</select>
    
</div>
                        
                    
                    
                        <div class="help">Hold down "Control", or "Command" on a Mac, to select more than one.</div>
                    
                </div>
            
        </div>
    
</fieldset>


  <fieldset class="module aligned collapse">
    <h2>高级设置</h2>
    
    
        <div class="form-row field-click_count">
            
            
                <div>
                    
                    
                        <label class="required" for="id_click_count">点击次数:</label>
                        
                            <input type="number" name="click_count" value="0" class="vIntegerField" required id="id_click_count" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-is_recommend">
            
            
                <div class="checkbox-row">
                    
                    
                        <input type="checkbox" name="is_recommend" id="id_is_recommend" /><label class="vCheckboxLabel" for="id_is_recommend">是否推荐</label>
                    
                    
                </div>
            
        </div>
    
</fieldset>













<div class="submit-row">
<input type="submit" value="保存文章" class="default" name="_save" />

</div>



    <script type="text/javascript"
            id="django-admin-form-add-constants"
            src="/static/admin/js/change_form.js"
            
                data-model-name="article"
            >
    </script>




<script type="text/javascript"
        id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>


</div>
</form></div>

        
        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

pythonWeb/education_project/templates/author.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block left_content %}
    <h1>王老师的文章</h1>
    <div class="topnews">
      <h2>最新文章</h2>

    {% for article in article_list %}
    <div class="blogs">
            <ul>
                      <h3><a href="{% url 'article' %}?id={{ article.id }}">{{ article.title }}</a></h3>
                                <p>{{ article.desc }}</p>
                                 <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>{% endfor %}</span><span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">
                                 浏览（{{ article.click_count }}）</span><span class="pingl f_r">评论（{{ article.comment_set.all.count }}）</span></p>
            </ul>
    </div>
    {% endfor %}
    </div>
    
    {% include 'pagination.html' %}
   
{% endblock %}

pythonWeb/education_project/templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{{ SITE_NAME }}</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<link href="{% static 'css/index.css' %}" rel="stylesheet">
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/sliders.js' %}"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->

</head>
<body>
<header>
  <div class="logo">
         <h1>{{ SITE_NAME }}</h1>
         <p>{{ SITE_DESC }}</p>
  </div>
  <nav id="topnav" class="f_r">
    <ul><!--target="_blank"-->
      <a href="/">首页</a> <a href="/my">关于我</a> <a href="/remen">文章</a><a href="/articleAdd">添加文章</a><a href="/userLead">用户排行榜</a>
      <!-- <a href="a.html" target="_blank">心情</a> <a href="c.html" target="_blank">相册</a> <a href="b.html" target="_blank">留言</a>-->
    </ul>
    <script src="js/nav.js"></script>
  </nav>
</header>
<article>
  <div class="l_box f_l">

      {% block left_content %}{% endblock %}
  </div>
  
  <div class="r_box f_r">
    <div class="tit01">
      <h3>关注我</h3>
      <div class="gzwm">
        <ul>
          <li><a class="xlwb" href="https://blog.csdn.net/qq_37786775" target="_blank">CSDN</a></li>
          <li><a class="txwb" href="https://www.jianshu.com/u/e6d35bb474be" target="_blank">简书</a></li>
          <li><a class="rss" href="" target="_blank">公众号</a></li>
          <li><a class="wx" href="">邮箱</a></li>
        </ul>
      </div>
    </div>
    <!--tit01 end-->
    <div class="moreSelect" id="lp_right_select">
      <script>
window.onload = function ()
{
  var oLi = document.getElementById("tab").getElementsByTagName("li");
  var oUl = document.getElementById("ms-main").getElementsByTagName("div");

  for(var i = 0; i < oLi.length; i++)
  {
    oLi[i].index = i;
    oLi[i].onmouseover = function ()
    {
      for(var n = 0; n < oLi.length; n++) oLi[n].className="";
      this.className = "cur";
      for(var n = 0; n < oUl.length; n++) oUl[n].style.display = "none";
      oUl[this.index].style.display = "block"
    }
  }
}
</script>
      <div class="ms-top">
        <ul class="hd" id="tab">
        <!--
          <li class="cur"><a href="/">浏览排行</a></li>
          <li><a href="/">评论排行</a></li>
          -->
          <li><a href="/">{{ strCom }}</a></li>
        </ul>
      </div>

      <div class="ms-main" id="ms-main">
        <div style="display: block;" class="bd bd-news" >
          <ul>
          {% for archive1 in article_list_recommend %}
            <li><a href="/article?id={{ archive1.id }}" target="_blank">{{ archive1.title }}</a></li>
            {% endfor %}
            
            
            {% for user in user_list %}
            <li><a href="/userLead?username={{ user.username }}" >{{ user.username }}</a></li>
            {% endfor %}
          </ul>
        </div>
        
        
        
       
        
        
        
        
        
        
        
        
        
        
        
        <div  class="bd bd-news">
          <ul>
            <li><a href="/" target="_blank">原来以为，一个人的勇敢是，删掉他的手机号码...</a></li>
            <li><a href="/" target="_blank">手机的16个惊人小秘密，据说99.999%的人都不知</a></li>
            <li><a href="/" target="_blank">住在手机里的朋友</a></li>
            <li><a href="/" target="_blank">教你怎样用欠费手机拨打电话</a></li>
            <li><a href="/" target="_blank">你面对的是生活而不是手机</a></li>
            <li><a href="/" target="_blank">豪雅手机正式发布! 在法国全手工打造的奢侈品</a></li>
          </ul>
        </div>

        <div class="bd bd-news">
          <ul>
            <li><a href="/" target="_blank">手机的16个惊人小秘密，据说99.999%的人都不知</a></li>
            <li><a href="/" target="_blank">你面对的是生活而不是手机</a></li>
            <li><a href="/" target="_blank">住在手机里的朋友</a></li>
            <li><a href="/" target="_blank">豪雅手机正式发布! 在法国全手工打造的奢侈品</a></li>
            <li><a href="/" target="_blank">教你怎样用欠费手机拨打电话</a></li>
            <li><a href="/" target="_blank">原来以为，一个人的勇敢是，删掉他的手机号码...</a></li>
          </ul>
        </div>
      </div>
      <!--ms-main end -->
    </div>
    <!--切换卡 moreSelect end -->

    <div class="cloud">
      <h3>标签云</h3>
      <ul>
        {% for tag in tag_list %}
        <li><a href="/remen?tagName={{ tag.name }}">{{ tag.name }}</a></li>
        {% endfor %}
      </ul>
    </div>
    <div class="tuwen">
      <h3>文章归档</h3>
      <ul>
        {% for archive in archive_list %}
        <li>
          <p><span class="tutime font-size-18"><a href=''>{{ archive }}</a></span></p>
        </li>
        {% endfor %}
      </ul>
    </div>
    <div class="links">
      <h3>友情链接</h3>
      <ul>
        <li><a href="/">web开发</a></li>
        <li><a href="/">前端设计</a></li>
        <li><a href="/">Html</a></li>
        <li><a href="/">CSS3</a></li>
        <li><a href="/">Html5+css3</a></li>
        <li><a href="/">百度</a></li>
      </ul>
    </div>
  </div>
  <!--r_box end -->
</article>
<footer>
  <p class="ft-copyright">cai的个人博客 蜀ICP备xxxxxxx号-1</p>
  <div id="tbox"> <a id="togbook" href="/"></a> <a id="gotop" href="javascript:void(0)"></a> </div>
</footer>
</body>
</html>

pythonWeb/education_project/templates/my.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>关于我</title>
</head>
<body>
XXX

</body>
</html>

pythonWeb/education_project/templates/pagination.html
{% load staticfiles %}
<div id="pagination">
    <ul id="pagination-flickr">
    {% if article_list.has_previous %}
    <li class="previous"><a href="?page={{ article_list.previous_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}{% if request.GET.cid %}&cid={{ request.GET.cid }}{% endif %}">&laquo;上一页</a></li>
    {% else %}
    <li class="previous-off">&laquo;上一页</li>
    {% endif %}
     <li class="active">{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li>
    {% if article_list.has_next %}
      <li class="next"><a href="?page={{ article_list.next_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}{% if request.GET.cid %}&cid={{ request.GET.cid }}{% endif %}">下一页 &raquo;</a></li>
    {% else %}
      <li class="next-off">下一页 &raquo;</li>
    {% endif %}
   </ul>
</div>

pythonWeb/education_project/templates/userLead.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block left_content %}

    <div class="topnews">
      <h2>{{ username }}  的文章</h2>

    {% for article in article_list %}
    <div class="blogs">
            <ul>
                      <h3><a href="{% url 'article' %}?id={{ article.id }}">{{ article.title }}</a></h3>
                                <p>{{ article.desc }}</p>
                                 <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>{% endfor %}</span><span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">
                                 浏览（{{ article.click_count }}）</span><span class="pingl f_r">评论（{{ article.comment_set.all.count }}）</span></p>
            </ul>
    </div>
    {% endfor %}
    </div>
    
    {% include 'pagination.html' %}
   
{% endblock %}